### ISSUE TITLE
do not use underscores in auth http headers

### ISSUE THREAD

**Issue by licarth** [Zoapp/zoauth#20]
They are dropped by nginx by default.

Currently,  `client_id` gets dropped by nginx if `underscores_in_headers` is not set to `'on'`.

**Comment by mikbry** [comment]
That's a known problem you should set in Nginx config :
underscores_in_headers on;

**Comment by licarth** [comment]
Yup, I did. But I only anticipate that it may cause problems in the future. Those times when you spend 2+ hours wondering why you have that error in the backend :smile:  
```
2018-05-24T12:46:15.301Z - error: error request error=Cannot read property 'error' of undefined, stack=TypeError: Cannot read property 'error' of undefined
    at exports.default.createUserBeforeBot (/src/dist/routes/bots.js:113:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7), code=undefined
```

**Comment by mikbry** [comment]
You should have leave a message for that trouble in #dev channel ;-)

client_id is a standard naming for OAuth2 so we can't change it.

**Comment by licarth** [comment]
I did : 
https://oplahq.slack.com/archives/C7AAYN11U/p1527166063000456

But the problem is that a missing header is not something easily identifiable. In that case, error message was not explicit. This only happened in a remote environment, not locally. Not so easy to identify in my opinion.

I just wanted to prevent people from having such issues in the future, especially if this lib is meant to be used by a broader audience, or different projects. A lot of people use `nginx`, and it may take them some time to realize where the issue comes from.

I do not think OAuth2 specs mentions underscores in headers, though.
